### ISSUE TITLE
AssertionError: Please assign one available GPU using CUDA_VISIBLE_DEVICES!

### ISSUE THREAD

**Issue by buhuiya** [wyf0912/SinSR#13]
Traceback (most recent call last):
  File "/home/cnu105/WJQ/code/SinSR-main/inference.py", line 129, in <module>
    main()
  File "/home/cnu105/WJQ/code/SinSR-main/inference.py", line 113, in main
    resshift_sampler = Sampler(
  File "/home/cnu105/WJQ/code/SinSR-main/sampler.py", line 52, in __init__
    self.setup_dist()  # setup distributed training: self.num_gpus, self.rank
  File "/home/cnu105/WJQ/code/SinSR-main/sampler.py", line 67, in setup_dist
    assert num_gpus == 1, 'Please assign one available GPU using CUDA_VISIBLE_DEVICES!'
AssertionError: Please assign one available GPU using CUDA_VISIBLE_DEVICES!

请问这是怎么回事呀

**Comment by AnhDuy26** [comment]
I am having the same error, can you please give me your solution. Thanks a lot.
