### ISSUE TITLE
Bug during Training (validation)

### ISSUE THREAD

**Issue by Hahaha732d** [wyf0912/SinSR#36]
Bug during Training(validation):                                                                                                                                                                                
Train: 002000/500000: loss:6.01e-01 mse:3.46e-02 mse_xT:5.35e-01 mse_gt:3.15e-02 lr:2.00e-05
Elapsed time: 3276.87s
====================================================================================================
Traceback (most recent call last):
  File "/home/Hall/SinSR/main_distill.py", line 49, in <module>
    trainer.train()
  File "/home/Hall/SinSR/trainer.py", line 284, in train
    self.validation()
  File "/home/Hall/SinSR/trainer.py", line 1220, in validation
    mean_clipiqa += self.metric_dict["clipiqa"](results.detach() * 0.5 + 0.5).sum().item()
  File "/home/Hall/miniconda3/envs/SinSRmym/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/Hall/miniconda3/envs/SinSRmym/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/Hall/miniconda3/envs/SinSRmym/lib/python3.10/site-packages/pyiqa/models/inference_model.py", line 100, in forward
    self.is_valid_input(target)
  File "/home/Hall/miniconda3/envs/SinSRmym/lib/python3.10/site-packages/pyiqa/models/inference_model.py", line 79, in is_valid_input
    assert x.min() >= 0 and x.max() <= 1, f'Input must be normalized to [0, 1], but got min={x.min():.4f}, max={x.max():.4f}'
AssertionError: Input must be normalized to [0, 1], but got min=-0.0640, max=1.1079

**Comment by LeonMeon** [comment]
Same here, I just made torch.clip(results.detach() * 0.5 + 0.5, 0, 1) before metrics' calculation

**Comment by txz32102** [comment]
> Same here, I just made torch.clip(results.detach() * 0.5 + 0.5, 0, 1) before metrics' calculation

It works!

**Comment by txz32102** [comment]
> Same here, I just made torch.clip(results.detach() * 0.5 + 0.5, 0, 1) before metrics' calculation

It works!
